# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data. Tensors are also optimized for automatic differentiation.

In [1]:
import torch
import numpy as np

## Initializing a Tensor

Tensors can be initialized in various ways. 

### Creating Tensors directly from data

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [3]:
data

[[1, 2], [3, 4]]

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

### Creating Tensors from a `NumPy` array

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
np_array

array([[1, 2],
       [3, 4]])

In [7]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

### Creating Tensors from `another tensor`

In [8]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [9]:
x_rand = torch.rand_like(x_data, dtype=torch.float)

In [10]:
x_rand

tensor([[0.7129, 0.4156],
        [0.4272, 0.6962]])

### Creating Tensors with Random or Constant Values

`shape` is a tuple of tensor dimensions.

In [11]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [12]:
rand_tensor

tensor([[0.5977, 0.6539, 0.0816],
        [0.3339, 0.4294, 0.4727]])

In [13]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [15]:
tensor = torch.rand(3,4)

In [16]:
tensor

tensor([[0.4656, 0.4031, 0.9804, 0.7231],
        [0.6354, 0.3347, 0.5629, 0.3448],
        [0.4325, 0.9788, 0.3252, 0.5718]])

In [17]:
print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

Over 100 tensor operations, including `arithmetic`, `linear algebra`, `matrix manipulation (transposing, indexing, slicing)`, `sampling` and more are comprehensively described in the pytorch documentation. 

<b>Refer to the link: <a href='https://pytorch.org/docs/stable/torch.html'>Tensor Operations</a> for more information.</b>

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU).

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using `.to` method.

<b>Note: Copying large tensors across devices can be expensive in terms of time and memory!</b>

In [18]:
# Check if the gpu is available or not
torch.cuda.is_available()

True

In [19]:
# Moving tensor to GPU is available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

Try out some of the operations from the above link. 

In [22]:
tensor = torch.ones(4,4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Standand numpy-like indexing and slicing:

In [23]:
print(f'First row: {tensor[0]}')

First row: tensor([1., 1., 1., 1.])


In [24]:
print(f'First column: {tensor[:,0]}')

First column: tensor([1., 1., 1., 1.])


In [25]:
print(f'Last Column: {tensor[:,-1]}')

Last Column: tensor([1., 1., 1., 1.])


In [28]:
#Setting the first column values to zero
tensor[:,1]=0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

`Joining tensors` For this we can use torch.cat to concatenate a sequence of tensors along a given dimension. 

In [29]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [38]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

## Arithmetic Operations

In [54]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [56]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [57]:
y2 = tensor.matmul(tensor.T)

In [58]:
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [59]:
y3 = torch.rand_like(tensor)
y3

tensor([[0.8298, 0.7659, 0.5898, 0.7368],
        [0.1617, 0.6218, 0.5670, 0.0049],
        [0.0914, 0.9410, 0.5421, 0.9339],
        [0.4315, 0.6643, 0.3250, 0.8635]])

In [60]:
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [61]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor

In [62]:
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [63]:
z2 = tensor.mul(tensor)
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [64]:
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Single-element tensors If we have a one-element tensor, for example by aggregating all values of a tensor into one value, we can convert it to a Python numerical value using item()

In [65]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [67]:
agg = tensor.sum()
agg

tensor(12.)

In [69]:
agg_item = agg.item()
agg_item

12.0

In [70]:
print(f'Type of agg: {type(agg)}')
print(f'Type of agg_item: {type(agg_item)}')

Type of agg: <class 'torch.Tensor'>
Type of agg_item: <class 'float'>


`In-place operations`: Operations that store the result into the operand are called in-place. They are denoted by a `_ ` suffix. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [71]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [72]:
tensor.add_(5)
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

<b> Note: In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.</b>

## Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [73]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [74]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

A change in the tensor reflects in the NumPy array.

In [75]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [76]:
t

tensor([2., 2., 2., 2., 2.])

In [77]:
n

array([2., 2., 2., 2., 2.], dtype=float32)

## NumPy array to Tensor

In [78]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.

In [79]:
np.add(n,1,out=n)

array([2., 2., 2., 2., 2.])

In [80]:
n

array([2., 2., 2., 2., 2.])

In [81]:
t

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)